### ISSUE TITLE
Improved documentation for stateful/complex widgets

### ISSUE THREAD

**Issue by kristianmandrup** [marko-js/marko-widgets#52]
Reading through the docs on stateful widget... the following was unclear to me:

```js
    isSelected: function() {
        return this.state.selected;
    }
```

Where is this used? explicitly or implicitly somehow?
And this:

```js
    getInitialState: function(input) {
        return {
            name: input.name,
            selected: input.selected || false;
        }
    },
```

I assume for selected to be true, I would have to set the selected attribute on the widget?

`<my-widget selected="true"/>`

Later...

`w-id="overlay"` - widget ID ?

` this.getWidget('overlay').show();`

Would be nice with a little more guidance/explanation :) Thanks!

**Comment by BryceEWatson** [comment]
Hi @kristianmandrup,
- The isSelected function is intended to give external access to the selected state variable. You could also call isSelected from within the widget if you want to have some standard logic wrapping how you return the value. 
- While there is no example in the readme, you can imagine isSelected being accessed here: https://github.com/marko-js/marko-widgets#referencing-nested-widgets
    - It could look something like this: 
```
if(this.getWidget('myToggle').isSelected()) {
    //Do Something
}
```
(@patrick-steele-idem, should I add this?)


- Yes, for selected to be true on initial render it would need to be passed in either on the widget attribute, or if rendered client-side, as part of the input model (https://github.com/marko-js/marko-widgets#client-side-rendering). This state object may be changed later, though, if some user action changes the state.
- The w-id attribute is explained in this section: https://github.com/marko-js/marko-widgets#referencing-nested-dom-elements

I hope this helps clarify, please let me know if you have any follow up questions!

**Comment by kristianmandrup** [comment]
Thanks guys. I will look further into the docs from the links you suggested...

On another note, regarding `input` vs `state` (and how do they relate to `widget.setProps()`?. 
So many names for different/similar kinds of state/data, lol %8-D
From the example:

```js
    getInitialState: function(input) {
        return {
            name: input.name,
            selected: input.selected || false;
        }
    },

    getTemplateData: function(state, input) {
        var style = ;

        return {
            name: state.name,
            color: state.selected ? 'yellow' : 'transparent'
        };
    },
```

I assume the following by logical deduction. `getInitialState` is a kind of constructor and is called with the initial input (via attributes in a marko template or `setProps` on client?) for the widget. 

The function returns (creates?) the initial widget state. Later in the (creation/update) life cycle, `getTemplateData` is called and now has the `state` available as an Object/hash so it can use it to be passed to the template. In the previous examples, since there was no  `getInitialState` defined, it had to use the `input` directly. Is this correct? Not exactly clear from the docs. Thanks!

I'm finally about ready to use these wonderful widgets. Got everything else mostly sorted out...
Cheers!

**Comment by kristianmandrup** [comment]
On yet another note: I seems like a Widget is a more advanced kind of custom tag since the examples place them in the `/components` folder. Do I still need to register them with `marko-taglib.json`? Do I still need a `marko-tag.json` file for validating incoming props?
Thanks :)

**Comment by patrick-steele-idem** [comment]
Hi @kristianmandrup, the difference between `state` and `input props` is that state is persisted with the widget (via `this.state`) and the `input props` are not persisted with the widget. On the initial rendering of a UI component embedded in a Marko template file, the `input props` will come from the attributes on the HTML tag for the UI component. You can also provide `input props` by calling `this.setProps(inputProps)` or by calling `require('my-ui-component').render(inputProps).appendTo(document.body)`.

Both `state` and `input props` are passed to `getTemplateData(state, input)` function (`input === input props`). Once the widget renders the initial `input props` are discarded by Marko Widgets. In comparison, the `state` returned by `getInitialState(input)` is stored in the widget's state property as observable object. Changing the value of any of the state properties using `this.setState(name, value)` will trigger a rerender of the widget using the new state. During the rerender the `input` will be `null` since the `input props` were discarded after the first rendering.

On a related not, if you call `this.setProps(newInputProps)` you are effectively rerendering from the "beginning".

I'm revisiting the docs with the v5 release so hopefully things will be less confusing.

**Comment by patrick-steele-idem** [comment]
> On yet another note: I seems like a Widget is a more advanced kind of custom tag since the examples place them in the /components folder. Do I still need to register them with marko-taglib.json? Do I still need a marko-tag.json file for validating incoming props?
Thanks :)

To Marko, UI components created using Marko Widgets are just standard custom tags. You will still need to register the tags using a `marko-taglib.json` and if you want to attach a schema to the custom tags then you will want to add a `marko-tag.json` for each tag directory. The only reason for putting them in the `components/` directory is because they form a complete UI component (HTML view + client-side behavior + styling). The `require('marko-widgets').defineComponent({...})` method exports a standard custom tag renderer function (i.e. `function(input, out)`) that is used by the Marko runtime to render the UI component.

**Comment by kristianmandrup** [comment]
Cool :) So it turns out my intuition, logical deduction was exactly right. Just wanted to be sure ;)
I'm sure your docs are getting progressively better all the time :)

**Comment by kristianmandrup** [comment]
I'm confused however whether a tag/widget should have an `index.js` or a `renderer.js` file as the ViewModel or "controller". I've seen both used, and using `renderer.js` has worked in my own trials, but I think `index.js` is more logical since that leverages node js require conventions directly.

**Comment by patrick-steele-idem** [comment]
I recommend using `index.js` for your UI components (no `renderer.js`). The only reason to use a `renderer.js` is for the [Split Renderer and Widget](https://github.com/marko-js/marko-widgets#split-renderer-and-widget) use case. The only reason you would split the renderer from the widget is if you are super concerned about page weight and you know that your widget will only be rendered on the server (rare).

**Comment by kristianmandrup** [comment]
`<div w-bind>` works just as well as `<div w-bind="true">` right? You can close issue after this ;)
Thanks again :)

**Comment by patrick-steele-idem** [comment]
`<div w-bind="true">` should not work unless I am mistaken. However, `<div w-bind>` and `<div w-bind="./index">` should both work.

**Comment by kristianmandrup** [comment]
ah, just asking since I'm using Jade to compile to marko.
Would have to be `div(w-bind='./index.js')` in Jade to work then, otherwise becomes: `<div w-bind="w-bind">` Thanks :)

**Comment by kristianmandrup** [comment]
Damn it. So many Qs...
I see this beauty :)

```html
<div class="alert alert-${data.type}" w-bind>
    <i class="alert-icon"/>
    <span w-body></span>
</div>
```

Is sth similar possible w regular custom tags? ie having a placeholder (like `w-body`) such that the widget becomes kind of like a layout?

**Comment by patrick-steele-idem** [comment]
If it helps, an attribute with no value is equivalent to an attribute with a value of an empty string:

```xml
<span w-body></span> === <span w-body=""></span>
```

The purpose of the `w-body` attribute is to support transclusion. If the user of a custom tag nested content inside the custom tag then that content will get injected into the output HTML relative to the `w-body` marker. In addition, if the widget rerenders then the body content will be preserved (since that content is external to the widget). For example, below is the usage of a custom tag with nested content:

```xml
<my-awesome-component>
    This is nested content that will be injected into the `w-body` element.
</my-awesome-component>
```
