### ISSUE TITLE
Stateful Widget with Update Handler JSLint Issue

### ISSUE THREAD

**Issue by baburammy** [marko-js/marko-widgets#58]
I have created a stateful widget and trying to use update handler. For Eg:- I have a state variable named 'second' and my update handler name is 'update_second'. But most of the lint tools are suggesting to use camelCase for the function names. 

Is there any future plan to change this update handler name to camel case?

**Comment by patrick-steele-idem** [comment]
Hmm. The underscore was selected because it simplified the logic needed to lookup a state handler method and the update methods stand out more from normal methods and they will less likely have a name conflict. We weren't thinking about jslint at the time, but I understand why you raised this issue.

 Here's the logic we are currently using to get a state handler method:

```javascript
var handlerMethodName = 'update_' + propName;
var handlerMethod = this[handlerMethodName];
```

If we were to use camel case the logic would be a little more complex and it would be a little slower:

```javascript
var handlerMethodName = 'update' + propName.charAt(1).toUpperCase() + propName.substring(1);
var handlerMethod = this[handlerMethodName];
```

Do you still think this is something we should consider or are you okay with using an underscore?

**Comment by yomed** [comment]
It's worth mentioning that this option has been deprecated in JSHint:
http://jshint.com/docs/options/#camelcase

And the corresponding rule in JSCS has an `ignoreProperties` mode which passes in this case:
http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers.html

**Comment by patrick-steele-idem** [comment]
My preference is to continue with the `update_foo` naming convention (if for no other reason that it would be a breaking change to switch). Unless there is a strong disagreement I will close this issue, but thank you for bringing up the issue.
