### ISSUE TITLE
accessing `this` inside getInitialState or getTemplateData

### ISSUE THREAD

**Issue by yomed** [marko-js/marko-widgets#73]
I've noticed that I can access `this` from the `init` method, but not from `getInitialState` or `getTemplateData`. Is this intentional?

For example I might have:

```
    getInitialState: function (input) {
        return {
            timeDisplay: getTimeDisplay(input.time)
        };
    },
```

`getTimeDisplay` has to be a private function. If I add it to the widget itself, I won't be be able to access it from `this.getTimeDisplay` because `this` is undefined.

**Comment by patrick-steele-idem** [comment]
That is intentional. The `getInitialState` and `getTemplateData` methods are used during rendering and during there is no widget instance (yet... especially since rendering can happen on the server). It's a little confusing that those methods are alongside the other methods that are part of the widget's prototype, but it was done that way for convenience. We need to make this clearer in the docs (on my list of things to do). If you have any suggestions please share.

**Comment by yomed** [comment]
Ah I see there are a bunch of `NOTE: This method is called during rendering and before a widget instance has been created. this should _not be used._` and `NOTE: this will be the widget instance`. Any objections if I remove the duplication by putting a notice at the top of the Lifecycle Methods section? It looks like all the "during rendering" methods have a `get` prefix, which should make the distinction easy, unless that's expected to change any time soon.

**Comment by patrick-steele-idem** [comment]
Maybe we should create a separate sub-section for "Rendering Methods" and "Widget Methods" below the "Lifecycle Methods" section?
