### ISSUE TITLE
Widget fails to load properly on initial page load only

### ISSUE THREAD

**Issue by pdcopeland727** [marko-js/marko-widgets#98]
Page does not work the first time after the server is started, but works after this initial load.

**Comment by patrick-steele-idem** [comment]
After investigating this issue offline I found that there is a bug related to asynchronous rendering and widget initialization order. A nested widget that renders asynchronously is getting initialized after the parent widget because of a bug in marko-widgets. In this particular use case, the rendering is only asynchronous the first time and after the first time it is cached and rendered synchronously.

The root cause is due to a typo in preserve the widget stack when beginning an asynchronous rendering.

**Comment by patrick-steele-idem** [comment]
New version published: `marko-widgets@5.0.2`
